"""
SafeCart Compliance Rules

These rules are used by the Auditor AI to validate
responses generated by the Worker AI.
"""


MAX_CORRECTION_ATTEMPTS = 3


# --------------------------------------------------
# Safety Rules
# --------------------------------------------------

SAFETY_RULES = [

    {
        "id": "RULE_001",
        "name": "No Fake Database Information",
        "description": (
            "The system must never invent order, product, "
            "inventory, price, refund, or delivery information."
        )
    },

    {
        "id": "RULE_002",
        "name": "Valid Refund Only",
        "description": (
            "A refund must only be approved when the order "
            "and product satisfy the refund policy."
        )
    },

    {
        "id": "RULE_003",
        "name": "No False Delivery Promise",
        "description": (
            "The system must never promise a delivery date "
            "that is not supported by available information."
        )
    },

    {
        "id": "RULE_004",
        "name": "Inventory Accuracy",
        "description": (
            "The system must not claim that a product is in stock "
            "unless the database confirms available inventory."
        )
    },

    {
        "id": "RULE_005",
        "name": "Price Accuracy",
        "description": (
            "The system must not invent or alter product prices."
        )
    },

    {
        "id": "RULE_006",
        "name": "Auditor Approval Required",
        "description": (
            "No Worker AI response should be sent to the customer "
            "without Auditor AI approval."
        )
    },

    {
        "id": "RULE_007",
        "name": "Maximum Correction Attempts",
        "description": (
            "The Worker AI may be corrected at most three times. "
            "After that, the request must be escalated or blocked."
        )
    }
]


# --------------------------------------------------
# Get Rules
# --------------------------------------------------

def get_rules():
    """
    Return all SafeCart safety rules.
    """
    return SAFETY_RULES


# --------------------------------------------------
# Refund Keywords
# --------------------------------------------------

REFUND_KEYWORDS = [
    "refund",
    "money back",
    "give my money back",
    "get my money back"
]


# --------------------------------------------------
# Return Keywords
# --------------------------------------------------
RETURN_KEYWORDS = [
    "return product",
    "return item",
    "send back",
    "want to return",
    "can i return",
    "i want to return"
]
# Delivery Keywords
# --------------------------------------------------

DELIVERY_KEYWORDS = [
    "delivery",
    "deliver",
    "arrive",
    "shipping",
    "when will",
    "delivery date",
    "how long will delivery take"
]


# --------------------------------------------------
# Order Status Keywords
# --------------------------------------------------

ORDER_STATUS_KEYWORDS = [
    "order status",
    "where is my order",
    "track my order",
    "track order",
    "order tracking",
    "status of my order",
    
]


# --------------------------------------------------
# Inventory / Availability Keywords
# --------------------------------------------------

INVENTORY_KEYWORDS = [
    "stock",
    "available",
    "inventory",
    "in stock",
    "availability",
    "how many items are available"
]


# --------------------------------------------------
# Price Keywords
# --------------------------------------------------

PRICE_KEYWORDS = [
    "price",
    "cost",
    "how much",
    "amount",
    "rate",
    "selling price"
]


# --------------------------------------------------
# Cancellation Keywords
# --------------------------------------------------

CANCELLATION_KEYWORDS = [
    "cancel order",
    "cancel my order",
    "cancellation",
    "cancel the order",
    "want to cancel",
    "can i cancel"
]


# --------------------------------------------------
# Product Information Keywords
# --------------------------------------------------

PRODUCT_INFO_KEYWORDS = [
    "product information",
    "product details",
    "tell me about this product",
    "tell me about",
    "more information",
    "more details",
    "what is this product",
    "details about this product",
    "details of",
    "features",
    "specifications",
    "description"
]


# --------------------------------------------------
# Policy Keywords
# --------------------------------------------------

POLICY_KEYWORDS = [
    "policy",
    "policies",
    "return policy",
    "refund policy",
    "delivery policy",
    "shipping policy",
    "what are your policies"
]


# --------------------------------------------------
# Complaint Keywords
# --------------------------------------------------

COMPLAINT_KEYWORDS = [
    "damaged",
    "wrong product",
    "wrong item",
    "problem with my order",
    "issue with my order",
    "complaint",
    "not received",
    "product is damaged",
    "received damaged"
]


# --------------------------------------------------
# Helper Function
# --------------------------------------------------

def contains_keyword(text, keywords):
    """
    Check whether text contains any keyword.
    """

    text = text.lower()

    return any(
        keyword.lower() in text
        for keyword in keywords
    )


# --------------------------------------------------
# Query Detection Functions
# --------------------------------------------------

def is_refund_query(query):
    return contains_keyword(
        query,
        REFUND_KEYWORDS
    )


def is_return_query(query):
    return contains_keyword(
        query,
        RETURN_KEYWORDS
    )


def is_delivery_query(query):
    return contains_keyword(
        query,
        DELIVERY_KEYWORDS
    )


def is_order_status_query(query):
    return contains_keyword(
        query,
        ORDER_STATUS_KEYWORDS
    )


def is_inventory_query(query):
    return contains_keyword(
        query,
        INVENTORY_KEYWORDS
    )


def is_price_query(query):
    return contains_keyword(
        query,
        PRICE_KEYWORDS
    )


def is_cancellation_query(query):
    return contains_keyword(
        query,
        CANCELLATION_KEYWORDS
    )


def is_product_info_query(query):
    return contains_keyword(
        query,
        PRODUCT_INFO_KEYWORDS
    )


def is_policy_query(query):
    return contains_keyword(
        query,
        POLICY_KEYWORDS
    )


def is_complaint_query(query):
    return contains_keyword(
        query,
        COMPLAINT_KEYWORDS
    )